# default config
defaults: [{ "": "default_config.yaml" }]

# distributed training
nodes: 1
gpus: 4 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: False # Use DataParallel instead of DistributedDataParallel
ddp: True # Use DistributedDataParallel
workers: 32

# train options
seed: 42 # sacred handles automatic seeding when passed in the config
batch_size: 8  # https://discuss.pytorch.org/t/do-dataparallel-and-distributeddataparallel-affect-the-batch-size-and-gpu-memory-consumption/97194
image_size: 256
start_epoch: 0
epochs: 100
dataset: "MSL"
#dataset_dir: "/home/goh/Documents/CLOVER/data/msl-labeled-data-set-v2.1"
dataset_dir: "/scratch/08452/kaipak/datasets/clover_all/msl-labeled-data-set-v2.1"
pretrain: False
num_classes: 19

# model options
resnet: "r50_1x_sk0"
projection_dim: 128 # "[...] to project the representation to a 128-dimensional latent space"

# loss options
optimizer: "Adam" # or LARS (experimental)
weight_decay: 1.0e-6 # "optimized using LARS [...] and weight decay of 10−6"
temperature: 0.5 # see appendix B.7.: Optimal temperature under different batch sizes

# reload options
#model_path: "models/simclr-hirise-pretrain-nc_1_4-bs_16" # set to the directory containing `checkpoint_##.tar`
#model_path: "save_hirise" # set to the directory containing `checkpoint_##.tar`
model_path: "models/simclr-hirise-pretrain-bs_1024-8n32g/" # set to the directory containing `checkpoint_##.tar`
epoch_num: 100 # set to checkpoint number
reload: False
reload_during_eval: True # whether to load checkpoint during eval
# if reload_during_eval = False and pretrain = False, a randomly initialized model will be evaluated
# if reload_during_eval = False and pretrain = /path/to/r50_1x_sk0.pth, the pretrained model will be evaluated

# logistic regression (linear eval) options
logistic_batch_size: 256
logistic_epochs: 500
save_features: False
zero_shot_eval: False
